### ISSUE TITLE
Failed to load resource: 

### ISSUE THREAD

**Issue by brije111** [MuhammedHasan/school-management-system#1]
Failed to load resource: font-awesome.min.css the server responded with a status of 404 (Not Found)

**Comment by MuhammedHasan** [comment]
Thanks for your comment but this is just a tutorial project to demonstrate angular to my colleagues when it was beta.  

You may simply replace this line with following line to solve issue.

<link href="css/font-awesome.min.css" rel="stylesheet">

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

However, the project is written in angular2-beta version thus it is outdated anyway. I do not update project because it is just a demo.
